name: Enforce Directory Structure

on:
  pull_request:
  push:

jobs:
  validate-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate directory structure
        run: python3 .github/scripts/check_directory_structure.py
